/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jokslibrary;

import java.util.ArrayList;
import java.util.List;

public class Library {
    public List<String> getJokes() {
        List<String> joke = new ArrayList<>();
        joke.add("Today at the bank, an old lady asked me to help check her balance. So I pushed her over.");
        joke.add("I bought some shoes from a drug dealer. I don't know what he laced them with, but I've been tripping all day.");
        joke.add("I told my girlfriend she drew her eyebrows too high. She seemed surprised.");
        joke.add("My dog used to chase people on a bike a lot. It got so bad, finally I had to take his bike away");
        joke.add("I'm so good at sleeping. I can do it with my eyes closed.");
        joke.add("My boss told me to have a good day.. so I went home.");
        joke.add("Why is Peter Pan always flying? He neverlands.");
        return joke;
    }
}
